* 概率论与数理统计
提供一套研究不确定事件的方式,因为在现实生活中,很多内容都是不确定的.难道不确定的内容就不能够定量的描述吗?
** 基本概念
*** 随机实验
简单理解就是结果不确定的实验
*** 样本空间
随机实验所有可能结果组成的集合
*** 随机事件
样本空间的子集
*** 随机变量
样本空间上的映射关系,一般是将样本空间映射到数字空间,方便计算.
**** 离散型随机变量
随机变量的取值是离散的
**** 连续型随机变量
随机变量的取值是连续的
*** 概率质量函数
离散型随即变量的概率分布,概率质量函数的取值>=0, <=1,而且概率总和为 1
*** 概率密度函数
给定范围,求面积才是对应的概率
*** 联合概率分布
多个随机变量的概率分布
*** 边缘概率
已知随机变量 x 和 y 的联合分布,求其中一个变量的概率分布

*** 条件概率
在实际生活中,我们经常遇到的是,当 A 发生的条件下,B 发生的概率.例如:如果他回来吃饭,晚上吃烤鱼的概率,在 A 发生的情况下 B 发生的概率
*** 乘法公式
求 A 和 B 同时发生的概率,A 发生的概率乘以在 A 发生的条件下 B 发生的概率
*** 全概率公式
已知 A 的概率和在 A 发生的条件下 B 的概率,求 B 发生的概率
*** 贝叶斯公式

*** 随机变量的数字特征
给定随机变量,如何分析它的规律,确定这组数的整体特征
**** 数学期望
随机变量的值乘以对应的概率值求和
**** 方差
随机变量和他的期望的差值平方随机变量的期望
** 常用的概率分布
*** 离散分布
概率分布函数确定之后,就可以直接给出他的期望和方差
**** 伯努利分布
随机变量的取值只有两个 0/1
**** 二项分布
重复 n 次的伯努利分布
**** 泊松分布
泊松分布适合于描述单位时间内随机事件发生的次数的概率分布
**** 几何分布
*** 连续分布
**** 正态分布

** 思考
概率是提高研究随机性的学科,他之所以存在就是因为未来是不确定的,人们生活在当下,但是又想要了解未来会发生什么事情,这也是人类不安全感的产物,而概率就是提供研究不确定事件的学科.还有一刚开始学习概率的时候,都是已知随机变量然后求概率分布,最后还有了数字特征,也就是期望和方差,但是不要忘记我们的初衷,之所以随机变量是我们的研究对象,就是因为他们我们现实中的不确定性,而最后的目标也是希望能够了解一种方法,能够获取在那些取值发生的概率会大一些,从而辅助我们决定应该选择随机变量的那个值.刚开始我们学习的时候,当然是正向的学习,但是实际在使用的过程中,都是首先假定概率分布,然后研究取那些值的概率比较大,从而选择对应的值,这也就达到了我们刚开始的目的.
在处理一个实际问题的时候,首先需要识别其中的要研究的对象是什么,样本空间是什么,然后假设对应的随机变量

明天会下雨吗? 会,不会 这个就是我们的样本空间 而 X 就是随机变量 例如 0 表示会下雨,1 表示不会下雨 而这个个人认为也是服从伯努利分布的

有一枚硬币,抛掷 100 次,正面朝上的次数 假设随机变量 X 表示正面朝上的次数,那么取值为 0-100,这个不就是二项分布吗? 一个事情发生 n 次之后,求某个结果的次数

进一步想,一个事情如果是必然的,那么就没有什么研究的必要,如果不是必然的,那么他就会有多个取值,如何从这么多取值中,取到比较好的结果这就是概率论想要解决的问题,上面抛掷硬币,通过概率分布还是,大概可以确定朝上的次数,那么我就可以知道朝上的大概的有多次,虽然也是不确定的,但是至少会踏实一些

